import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppHeader from "./components/Header";

const poppins = Poppins({
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} antialiased`}>
        <AppHeader />
        <div className="px-4 sm:px-6 md:px-8 lg:px-16 min-w-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
